name: docker

on:
  push:
    tags:
      - '**'

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      DOCKER_BUILDKIT: 1
    steps:
      - uses: actions/checkout@v2
      - uses: docker/build-push-action@v1
        with:
          registry: ghcr.io
          repository: ${{ secrets.GITHUB_USERNAME }}/tf2rl/cpu
          tags: ${{ github.ref }}, latest
          username: ${{ secrets.GITHUB_USERNAME }}
          password: ${{ secrets.GHCR_TOKEN }}
          dockerfile: Dockerfile
          always_pull: true
      - uses: docker/build-push-action@v1
        with:
          registry: ghcr.io
          repository: ${{ secrets.GITHUB_USERNAME }}/tf2rl/nvidia
          tags: ${{ github.ref }}, latest
          username: ${{ secrets.GITHUB_USERNAME }}
          password: ${{ secrets.GHCR_TOKEN }}
          dockerfile: Dockerfile.nvidia
          always_pull: true
